title: Cloud platform user guide

permalink: pretty

defaults:
  -
    scope:
      path: "deploying-an-app"
    values:
      deploying-an-app: true
  -
    scope:
      path: "getting-started"
    values:
      getting-started: true
  -
    scope:
      path: "other-topics"
    values:
      other-topics: true
