title: Cloud platform user guide

permalink: pretty

defaults:
  -
    scope:
      path: "01-getting-started"
    values:
      01-getting-started: true
  -
    scope:
      path: "02-deploying-an-app"
    values:
      02-deploying-an-app: true
  -
    scope:
      path: "03-other-topics"
    values:
      03-other-topics: true
