title: Cloud platform user guide

permalink: pretty

defaults:
  -
    scope:
      path: "overview"
    values:
      overview: true
  -
    scope:
      path: "getting-started"
    values:
      getting-started: true
  -
    scope:
      path: "cloud-platform"
    values:
      cloud-platform: true
